---
# handlers file for ansible-role-consul

- name: Restart consul
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: true
